spring:
    application:
        name: challenge-wl
    datasource:
        url: jdbc:postgresql://localhost:5432/challenge-wl
        username: postgres
        password: 748596123
        driver-class-name: org.postgresql.Driver
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
          hibernate:
              format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 1000
logging:
    level:
      org:
          springframework:
              security: DEBUG